services:
  - type: web
    name: webserver
    region: oregon
    env: node
    plan: starter
    buildCommand: yarn install --frozen-lockfile --production=false; yarn build;
    startCommand: yarn prod:start
    envVars:
      - key: NODE_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: elasticURL
        fromService:
          name: elasticsearch
          type: pserv
          property: hostport
      - fromGroup: secrets
  - type: worker
    name: updater
    region: oregon
    env: node
    buildCommand: yarn install --frozen-lockfile --production=false; yarn build;
    startCommand: yarn prod:start:updater
    envVars:
      - key: NODE_ENV
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: elasticURL
        fromService:
          name: elasticsearch
          type: pserv
          property: hostport
      - fromGroup: secrets
  - type: pserv
    name: elasticsearch
    env: docker
    plan: standard
    disk:
      name: esdata
      mountPath: /usr/share/elasticsearch/data
      sizeGB: 10
    autoDeploy: false # so ES does not restart on a push to this repository.
    envVars:
    - key: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
    - key: discovery.type
      value: single-node
    - key: cluster.name
      value: elastic

databases:
  - name: postgres
    region: oregon
    plan: starter

envVarGroups:
- name: secrets
  envVars:
  - key: fbAppSecret
    sync: false
  - key: fbToken
    sync: false
  - key: fbVerifyToken
    sync: false
  - key: rollbarPostServerItemToken
    sync: false